from tkinter import *

root = Tk()
root.geometry("800x600")
root.title("Basic GUI")
root.configure(bg="light green")

f1 = Frame(root,bg="dark green",borderwidth=3,relief=SUNKEN)
f1.place(x=10,y=50)
f2 = Frame(root,bg="dark green",borderwidth=3,relief=SUNKEN)
f2.place(x=10,y=100)
f3 = Frame(root,bg="dark green",borderwidth=3,relief=SUNKEN)
f3.place(x=10,y=150)
f4 = Frame(root,bg="dark green",borderwidth=3,relief=SUNKEN)
f4.place(x=10,y=200)
f5 = Frame(root,bg="dark green",borderwidth=3,relief=SUNKEN)
f5.place(x=10,y=250)
f6 = Frame(root,bg="forestgreen",borderwidth=5,relief=FLAT)
f6.place(x=400,y=30)

l1 = Label(f1,text="Profile",fg="black")
l1.pack()
l2 = Label(f2,text="Setting",fg="black")
l2.pack()
l3 = Label(f3,text="Logout",fg="black")
l3.pack()
l4 = Label(f4,text="About Us",fg="black")
l4.pack()
l5 = Label(f5,text="feedback",fg="black")
l5.pack()
l6 = Label(f6,text="content",fg="black")
l6.pack(anchor="s")

root.mainloop()